config/routes.rb
Rails.application.routes.draw do
  root to: 'ideas#welcome'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: "sessions#destroy"
  get '/users/:user_id/ideas', to: "users#ideas"

  resources :users do
    resources :ideas, except: [:index]
  end

  namespace :admin do
    resources :categories
  end

  resources :ideas
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/idea.rb
require 'fotofetch'

class Idea < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  def image
    links = Fotofetch::Fetch.new.fetch_links(self.title)
    links.values.pop
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :ideas

  enum role: %w(default admin)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def welcome
  end

  def index
    @ideas = Idea.all
  end

  def new
    unless current_user == User.find(params[:user_id])
      render file: '/public/404'
    else
      @idea = Idea.new
      @user = current_user
    end
  end

  def create
    @user = current_user
    @idea = @user.ideas.new(idea_params)
    if @idea.save
      redirect_to idea_path(@idea)
    else
      render :new
    end
  end

  def show
    @idea = Idea.find(params[:id])
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to ideas_path
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def ideas
    @ideas = current_user.ideas
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= form_for(@category) do |f| %>
  <%= f.label :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/ideas/index.html.erb
<div class="container">

  <h1 class="center">Idea Hub</h1>

  <% @ideas.each do |idea| %>
    <div class="container">

      <div class="card">
        <div class="card-image">
          <img src="<%= idea.image %>" width="250" height="250" algorithm="fill_proportional">
          <span class="card-title"><%= idea.title %></span>
        </div>
        <div class="card-content">
          <p><%= idea.description %></p>
        </div>
        <div class="card-action">
          <%= link_to "Show", idea_path(idea) %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/ideas/new.html.erb
<%= form_for([@user, @idea]) do |f| %>
  <%= f.text_field :title, placeholder: "Title" %> 
  <%= f.text_field :description, placeholder: "Description" %>
  <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true %>
  <%= f.submit %>
<% end %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>
<%= image_tag @idea.image, id: "idea_image" %>
<p><%= @idea.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaGroup</title>
     <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="#3949ab indigo darken-1">
      <div class="nav-wrapper">
        <!-- <a href="/ideas" class="brand-logo">IDEA HUB</a> -->
        <%= link_to "IDEA HUB", ideas_path, { class: "brand-logo"} %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if current_user %>
            <%= link_to "\"I HAVE AN IDEA!\"", new_user_idea_path(current_user) %>
            <%= link_to "Create Category", new_admin_category_path %>
            <%= link_to "Log Out", logout_path, method: "delete" %>
          <% else %>
            <%= link_to "Register New User", new_user_path  %>
            <%= link_to "Log In", login_path %>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  </body>
</html>

app/views/users/ideas.html.erb
<h1>Your Ideas</h1>

<% @ideas.each do |idea| %>
  <div class="card"
    <div class="card-image">
      <img src="<%= idea.image %>" width="250" height="250" algorithm="fill_proportional">
      <span class="card-title"><%= idea.title %></span>
    </div>
    <div class="card-content">
      <p><%= idea.description %></p>
    </div>
    <div class="card-action">
      <%= link_to "Show", idea_path(idea) %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Register New Account</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :username  %>
  <%= f.text_field :username  %>
  <%= f.label :email  %>
  <%= f.text_field :email  %>
  <%= f.label :password  %>
  <%= f.password_field :password  %>
  <%= f.submit "Register!"%>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Dashboard</h1>

<p>Score: <%= @user.score %></p>

<%= link_to "All Ideas", ideas_path  %>
<%= link_to "New Idea", new_user_idea_path(@user) %>
<%= link_to "Your Ideas", user_ideas_path(@user)  %>